[[plugins]]
repo = 'scrooloose/syntastic'
on_i = 1
hook_add = '''
    " for python
    let g:syntastic_python_checkers = ["pyflakes", "pep8"]
'''

#[[plugins]]
#repo = 'kevinw/pyflakes-vim'
#on_ft = ['python', 'python3']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3']
hook_add = '''
    " for python
    "" jedi-vim
    autocmd FileType python setlocal omnifunc=jedi#completions completeopt-=preview
    let g:jedi#completions_enabled = 0
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#popup_select_first = 0
    let g:jedi#popup_on_dot = 0
    let g:jedi#documentation_command = "K"
    if !exists('g:neocomplete#force_omni_input_patterns')
        let g:neocomplete#force_omni_input_patterns = {}
    endif
    if has('lua')
        let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w*'
    endif
'''
